#include "MainWindow.h"
#include <QApplication>

int main(int argc, char *argv[])
{
	QApplication a(argc, argv);
	MainWindow w;
	a.setStyleSheet("QMenu{"
					"background-color:white;"
					"border: 1px solid #b2b2b2;"
					"}"
					"QMenuBar{"
					"background-color:white;"
					"border: 1px solid #b2b2b2;"
					"}"
					"#prevButton{"
					"border-image:url(:/images/easy/previous.png);"
					"}"
					"#playButton[is_playing=true]{"
					"border-image:url(:/images/easy/pause.png);"
					"}"
					"#playButton[is_playing=false]{"
					"border-image:url(:/images/easy/play.png);"
					"}"
					"#nextButton{"
					"border-image:url(:/images/easy/next.png);"
					"}"
					"#volumeButton[is_mute=true]{"
					"border-image:url(:/images/easy/mute.png);"
					"}"
					"#volumeButton[is_mute=false]{"
					"border-image:url(:/images/easy/volume.png);"
					"}"
					"#playbackModeButton[playbackmode=\"loop\"]{"
					"border-image:url(:/images/easy/loop.png);"
					"}"
					"#playbackModeButton[playbackmode=\"current_loop\"]{"
					"border-image:url(:/images/easy/current_loop.png);"
					"}"
					"#playbackModeButton[playbackmode=\"sequential\"]{"
					"border-image:url(:/images/easy/sequential.png);"
					"}"
					"#playbackModeButton[playbackmode=\"random\"]{"
					"border-image:url(:/images/easy/random.png);"
					"}"
					"#playlistButton{"
					"border-image:url(:/images/easy/playlistbutton.png);"
					"}"
					"QMenu::item{"
					"color:black;"
					"border:1px soild #b2b2b2;"
					"background-color:white;"
					"padding:2px 16px;"
					"margin:2px 2px;"
					"}"
					"QMenu::item::selected{"
					"background-color:#00a1ec;"
					"}"
					"QMainWindow{"
					"background-color:white;"
					"}"
					"#PlaylistView,#LocalMusicView{"
					"color: black;"
					"qproperty-showGrid:false;"
					"qproperty-alternatingRowColors:true;"
					"background-color:white;"
					"alternate-background-color:#eeeeee;"
					"selection-color:black;"
					"selection-background-color:#cccccc;"
					"border-radius: 0px;"
					"padding: 2px 4px;}"
					"QTabWidget:tab-bar{"
					"border-color:white;"
					"}"
					"QSlider::add-page:horizontal"
					"{"
					"background-color:#b2b2b2;"
					"}"
					"QSlider::sub-page:horizontal"
					"{"
					"background-color:#00a1ec;"
					"}"
					"QSlider::groove:horizontal"
					"{"
					"background:transparent;"
					"height:6px;"
					"}"
					"QSlider::handle:horizontal"
					"{"
					"height:20px;"
					"width:10px;"
					"background:white;"
					"border: 1px solid #b2b2b2;"
					"margin: -8 0px;"
					"}");
	w.show();
	return a.exec();
}
